
services:
  db:
    image: postgres:16
    container_name: pharmacy-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pharalert
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
      image: axllent/mailpit
      container_name: pharmacy-mailpit
      restart: always
      ports:
        - "1025:1025"
        - "8025:8025"

volumes:
  pgdata:
