// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node seed.js"
  },
  datasource: {
    // for local database
    url: process.env["DATABASE_URL"],
    // for server database
    // url: process.env["DIRECT_URL"],
  },
});
